services:
  db:
    image: mysql:5.7
    container_name: snaphub_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init_snaphub.sql:/docker-entrypoint-initdb.d/init_snaphub.sql
    ports:
      - "3306:3306"

    healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
         interval: 10s
         timeout: 5s
         retries: 5

  app:
    build:
      context: .                  # Указывает на использование текущей директории как контекст сборки
      dockerfile: Dockerfile      # Указывает имя Dockerfile (если файл называется просто "Dockerfile", можно не указывать)
    container_name: snaphub_app
    environment:
      ACCESS_KEY: ${ACCESS_KEY}
      MASTER_KEY: ${MASTER_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"               # Настройте этот порт на то, какой у вас используется в Go приложении
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data:
